"""Tool schemas for commercial banking."""
from __future__ import annotations

from core.tool_schemas import I, N, S, _t
from envs.commercial_banking.policy import ACTION_CODES

SYSTEM_A = "credit_workbench"
SYSTEM_B = "ncino_core"


def make_tools() -> list[dict]:
    return [
        _t("list_credit_requests",
           "List open credit requests in the workbench.", {}, []),
        _t("get_request", "Get one credit request and its workflow state.",
           {"request_id": S}, ["request_id"]),
        _t("list_report_templates",
           "List report format options. Check corrupt flags before choosing.",
           {"request_type": {**S, "description": "optional filter"}}, []),
        _t("get_template", "Get one report template including required_sections.",
           {"template_id": S}, ["template_id"]),
        _t("get_report_requirements",
           "Return the selected template's exact section checklist and what remains to write.",
           {"request_id": S}, ["request_id"]),
        _t("list_products", f"List credit products in {SYSTEM_B}.", {}, []),
        _t("list_covenants", "List covenants, optionally filtered by product_code.",
           {"product_code": S}, []),
        _t("search_prior_deals", "Search archived prior deals and materials.",
           {"query": S}, ["query"]),
        _t("list_web_digests", "List web/news financial digests for a customer.",
           {"customer_name": S}, ["customer_name"]),
        _t("get_web_digest", "Get one digest by id.",
           {"digest_id": S}, ["digest_id"]),
        _t("search_customers",
           f"Fuzzy search customers in {SYSTEM_B}. Inspect with get_customer "
           "before writing — search omits record_status.",
           {"query": S}, ["query"]),
        _t("get_customer", "Get one customer including record_status.",
           {"customer_id": S}, ["customer_id"]),
        _t("get_spread_job", "Get spreading job status and returned lines.",
           {"job_id": S}, ["job_id"]),
        _t("get_deal", "Get one nCino deal.",
           {"deal_id": S}, ["deal_id"]),
        _t("select_report_template",
           "Select the report format for a request.",
           {"request_id": S, "template_id": S},
           ["request_id", "template_id"]),
        _t("create_excel_model",
           "Create an Excel model shell linked to a digest.",
           {"request_id": S, "digest_id": S},
           ["request_id", "digest_id"]),
        _t("write_model_cells",
           "Write financial model cells including computed leverage.",
           {"model_id": S, "revenue": N, "ebitda": N, "total_debt": N,
            "interest_expense": N, "leverage": N},
           ["model_id", "revenue", "ebitda", "total_debt",
            "interest_expense", "leverage"]),
        _t("submit_to_spreading",
           "Send the model to the spreading team. Results may contain errors.",
           {"request_id": S, "model_id": S}, ["request_id", "model_id"]),
        _t("correct_spread_lines",
           "Correct spread line values and mark the job checked.",
           {"job_id": S,
            "corrections": {"type": "object",
                            "additionalProperties": N,
                            "description": "map of line_key -> correct value"}},
           ["job_id", "corrections"]),
        _t("mark_spread_checked",
           "Mark a spread job checked when returned lines already match the model.",
           {"job_id": S}, ["job_id"]),
        _t("write_report_section",
           "Write one report section. Titles must match the selected template; "
           "the response reports remaining_sections, so continue until it is empty.",
           {"request_id": S, "template_id": S, "section_title": S,
            "section_body": S, "section_ord": I},
           ["request_id", "template_id", "section_title",
            "section_body", "section_ord"]),
        _t("push_deal_ncino",
           "Push the deal into nCino. Subject to delegated limit authority.",
           {"request_id": S, "customer_id": S, "product_code": S,
            "limit_amount": N, "template_id": S},
           ["request_id", "customer_id", "product_code",
            "limit_amount", "template_id"]),
        _t("update_system_covenants",
           "Write covenant test results into systems of record for a deal.",
           {"deal_id": S, "covenant_id": S, "tested_value": N,
            "compliance_status": {**S, "enum": ["compliant", "breach", "not_tested"]}},
           ["deal_id", "covenant_id", "tested_value", "compliance_status"]),
        _t("update_system_pricing",
           "Write pricing terms into systems of record for a deal.",
           {"deal_id": S, "rate_bps": I, "fee_bps": I},
           ["deal_id", "rate_bps", "fee_bps"]),
        _t("log_action",
           f"Append an entry to the {SYSTEM_B} audit log.",
           {"actor": S,
            "action": {**S, "enum": list(ACTION_CODES)},
            "target_system": {**S, "enum": [SYSTEM_A, SYSTEM_B]},
            "target_key": S, "note": S},
           ["actor", "action", "target_system", "target_key", "note"]),
        _t("request_approval",
           "Escalate a change beyond your authority. Does not modify records.",
           {"target": S, "proposed_change": S, "rationale": S},
           ["target", "proposed_change", "rationale"]),
        _t("finish", "Call when the credit request workflow is complete.",
           {"summary": S}, ["summary"]),
    ]
